# -*- coding: utf-8 -*-
"""Copy_of_Copy_of_Copy_of_Exe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18SR_tqR1QaNYA9lDISZ7LtgrMBxllpPw
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
!pwd
# %cd /content/drive/My Drive/chatbot/ASRproject_0919

"""**Generate the shell**"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install google-colab-shell
!python -m venv stt --without-pip

!source stt/bin/activate

!pip install -r requirements.txt
!pip install fastapi uvicorn sqlmodel transformers torch peft python-multipart accelerate sounddevice guidance

!apt-get update -qq
!apt-get install -y -qq ffmpeg

!pip install --upgrade torch
!pip install git+https://github.com/huggingface/transformers triton==3.4 kernels
!pip uninstall torchvision torchaudio -y
!pip install gpustat
!pip install gpt-oss
!pip install guidance
!pip install pydantic

!pip install pyngrok
!sudo apt-get install libportaudio2

"""**Initiate the patient.db**"""

# !python db_migrate_1001.py

"""Auth code: 2zedNCm3w45DxNlOq86d4iUNb47_5ZmQ5zvWTeF6kNEkHbAX9"""

from pyngrok import ngrok
import getpass

print("Enter your ngrok authtoken:")
authtoken = getpass.getpass()
ngrok.set_auth_token(authtoken)

"""Now, you can start the `ngrok` tunnel to your server, which is running on port 8000."""

ngrok_tunnel = ngrok.connect(8000)
print(f"Public URL: {ngrok_tunnel.public_url}")

'''
# Linux/Colab
!lsof -i:8000          # see which PID is holding the port
!kill -9 $(lsof -t -i:8000)

# or, more direct:
!pkill -f "uvicorn.*8000"
'''

"""You can use the `Public URL` provided in the output to access your application."""

!uvicorn app.main:app --reload

"""**Read the table**"""

!pip install sqlite3

import sqlite3

conn = sqlite3.connect('patient.db')

cursor = conn.cursor()
cursor.execute("SELECT * FROM patient")
rows = cursor.fetchall()
for row in rows:
    print(row)

