# -*- coding: utf-8 -*-
"""Copy of Copy of Copy of Copy of Exe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJ9R5JVj9Q6NObmBgTIZkG0zQfG6ePBq
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')

# %cd /content/drive/My Drive/chatbot/graph_rag

"""**Generate the shell**"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install google-colab-shell
!python -m venv graphrag --without-pip

# Commented out IPython magic to ensure Python compatibility.
!source graphrag/bin/activate

# %pip install -r requirements.txt

!pip install pyngrok

"""Auth code: 2zedNCm3w45DxNlOq86d4iUNb47_5ZmQ5zvWTeF6kNEkHbAX9"""

from pyngrok import ngrok
import getpass

print("Enter your ngrok authtoken:")
authtoken = getpass.getpass()
ngrok.set_auth_token(authtoken)

"""Now, you can start the `ngrok` tunnel to your server, which is running on port 8000."""

ngrok_tunnel = ngrok.connect(8000)
print(f"Public URL: {ngrok_tunnel.public_url}")

"""You can use the `Public URL` provided in the output to access your application."""

!uvicorn app.main:app --reload

